version: '3.8'

services:
  web:
    container_name: hiring_form
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 hiring_form_project.wsgi:application
    ports:
      - 8000:8000
