version: '3.8'

services:
  web:
    container_name: hiring_form
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 hiring_form_project.wsgi:application
    labels:
      traefik.enable: true
      traefik.http.routers.hiring_form.rule: Host(`dc.studsovet.me`)
      traefik.http.services.hiring_form.loadbalancer.server.port: 8000
