version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 hiring_form_project.wsgi:application
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dc.studsovet.me`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
