version: '3.8'

services:
  web:
    container_name: hiring_form
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 hiring_form_project.wsgi:application
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.hiring_form.entrypoints: https
      traefik.http.routers.hiring_form.tls: true
      traefik.http.routers.hiring_form.tls.certresolver: myresolver
      traefik.http.routers.hiring_form.rule: Host(`dc.studsovet.me`)
      traefik.http.services.hiring_form.loadbalancer.server.port: 8000
      traefik.http.routers.hiring_form.middlewares: redirect-regex-hiring
      traefik.http.middlewares.redirect-regex-hiring.stripprefix.prefixes: /hiring
      

networks:
  proxy:
    external: true
