version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:8000 hiring_form_project.wsgi:application
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`dc.studsovet.me`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`status.studsovet.me`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$3KSFGnyt$$PvFdsfteY8Br2DpplfsZR/"

volumes:
  traefik-public-certificates:
