entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
accessLog: {}
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
certificatesResolvers:
  letsencrypt:
    acme:
      email: hsedigitalcommittee@gmail.com
      storage: /certificates/acme.json
      httpChallenge:
        entryPoint: web
